In [1]:
import piplite
await piplite.install(['numpy'])
await piplite.install(['pandas'])
await piplite.install(['seaborn'])

In [2]:
# Pandas is a software library written for the Python programming language for data manipulation and analysis.
import pandas as pd
# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
import numpy as np
# Matplotlib is a plotting library for python and pyplot gives us a MatLab like plotting framework. We will use this in our plotter function to plot data.
import matplotlib.pyplot as plt
#Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics
import seaborn as sns
# Preprocessing allows us to standarsize our data
from sklearn import preprocessing
# Allows us to split our data into training and testing data
from sklearn.model_selection import train_test_split
# Allows us to test parameters of classification algorithms and find the best one
from sklearn.model_selection import GridSearchCV
# Logistic Regression classification algorithm
from sklearn.linear_model import LogisticRegression
# Support Vector Machine classification algorithm
from sklearn.svm import SVC
# Decision Tree classification algorithm
from sklearn.tree import DecisionTreeClassifier
# K Nearest Neighbors classification algorithm
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import confusion_matrix



<ipython-input-2-a4f6573f6dfb>:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
from js import fetch
import io

URL1 = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_2.csv"
resp1 = await fetch(URL1)
text1 = io.BytesIO((await resp1.arrayBuffer()).to_py())
data = pd.read_csv(text1)
data.head()

URL2 = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_3.csv'
resp2 = await fetch(URL2)
text2 = io.BytesIO((await resp2.arrayBuffer()).to_py())
X = pd.read_csv(text2)
X.head(100)


FlightNumber   PayloadMass  Flights  Block  ReusedCount  Orbit_ES-L1  \
0            1.0   6104.959412      1.0    1.0          0.0          0.0   
1            2.0    525.000000      1.0    1.0          0.0          0.0   
2            3.0    677.000000      1.0    1.0          0.0          0.0   
3            4.0    500.000000      1.0    1.0          0.0          0.0   
4            5.0   3170.000000      1.0    1.0          0.0          0.0   
..           ...           ...      ...    ...          ...          ...   
85          86.0  15400.000000      2.0    5.0          2.0          0.0   
86          87.0  15400.000000      3.0    5.0          2.0          0.0   
87          88.0  15400.000000      6.0    5.0          5.0          0.0   
88          89.0  15400.000000      3.0    5.0          2.0          0.0   
89          90.0   3681.000000      1.0    5.0          0.0          0.0   

    Orbit_GEO  Orbit_GTO  Orbit_HEO  Orbit_ISS  ...  Serial_B1058  \
0         0.0        0.0        0.0        0.0  ...           0.0   
1         0.0        0.0        0.0        0.0  ...           0.0   
2         0.0        0.0        0.0        1.0  ...           0.0   
3         0.0        0.0        0.0        0.0  ...           0.0   
4         0.0        1.0        0.0        0.0  ...           0.0   
..        ...        ...        ...        ...  ...           ...   
85        0.0        0.0        0.0        0.0  ...           0.0   
86        0.0        0.0        0.0        0.0  ...           1.0   
87        0.0        0.0        0.0        0.0  ...           0.0   
88        0.0        0.0        0.0        0.0  ...           0.0   
89        0.0        0.0        0.0        0.0  ...           0.0   

    Serial_B1059  Serial_B1060  Serial_B1062  GridFins_False  GridFins_True  \
0            0.0           0.0           0.0             1.0            0.0   
1            0.0           0.0           0.0             1.0            0.0   
2            0.0           0.0           0.0             1.0            0.0   
3            0.0           0.0           0.0             1.0            0.0   
4            0.0           0.0           0.0             1.0            0.0   
..           ...           ...           ...             ...            ...   
85           0.0           1.0           0.0             0.0            1.0   
86           0.0           0.0           0.0             0.0            1.0   
87           0.0           0.0           0.0             0.0            1.0   
88           0.0           1.0           0.0             0.0            1.0   
89           0.0           0.0           1.0             0.0            1.0   

    Reused_False  Reused_True  Legs_False  Legs_True  
0            1.0          0.0         1.0        0.0  
1            1.0          0.0         1.0        0.0  
2            1.0          0.0         1.0        0.0  
3            1.0          0.0         1.0        0.0  
4            1.0          0.0         1.0        0.0  
..           ...          ...         ...        ...  
85           0.0          1.0         0.0        1.0  
86           0.0          1.0         0.0        1.0  
87           0.0          1.0         0.0        1.0  
88           0.0          1.0         0.0        1.0  
89           1.0          0.0         0.0        1.0  

[90 rows x 83 columns]

In [4]:
data.head()
data.info()
X.head()
X.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   FlightNumber    90 non-null     int64  
 1   Date            90 non-null     object 
 2   BoosterVersion  90 non-null     object 
 3   PayloadMass     90 non-null     float64
 4   Orbit           90 non-null     object 
 5   LaunchSite      90 non-null     object 
 6   Outcome         90 non-null     object 
 7   Flights         90 non-null     int64  
 8   GridFins        90 non-null     bool   
 9   Reused          90 non-null     bool   
 10  Legs            90 non-null     bool   
 11  LandingPad      64 non-null     object 
 12  Block           90 non-null     float64
 13  ReusedCount     90 non-null     int64  
 14  Serial          90 non-null     object 
 15  Longitude       90 non-null     float64
 16  Latitude        90 non-null     float64
 17  Class           90 non-null     int64

(90, 83)

In [5]:

Y = data['Class'].to_numpy()
transform = preprocessing.StandardScaler()
X_scaled = transform.fit_transform(X)
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=2)
X_train.shape, X_test.shape

((72, 83), (18, 83))

In [6]:
def run_model(name, estimator, params, X_train, X_test, Y_train, Y_test):
    grid = GridSearchCV(estimator, params, cv=10)
    grid.fit(X_train, Y_train)
    yhat = grid.predict(X_test)
    cm = confusion_matrix(Y_test, yhat)
    acc = grid.score(X_test, Y_test)
    print(f"{name} best params :", grid.best_params_)
    print(f"{name} CV accuracy:", grid.best_score_)
    print(f"{name} test acc   :", acc)
    print("Confusion matrix:\n", cm, "\n")
    return cm, acc, grid

def run_logreg(X_train, X_test, Y_train, Y_test):
    params = {"C": [0.01, 0.1, 1],"penalty": ["l2"], "solver": ["lbfgs"]}
    return run_model("Logistic Regression", LogisticRegression(), params, X_train, X_test, Y_train, Y_test)

def run_svm(X_train, X_test, Y_train, Y_test):
    params = {
        "kernel": ("linear", "rbf", "poly", "rbf", "sigmoid"),
        "C": np.logspace(-3, 3, 5),
        "gamma": np.logspace(-3, 3, 5),}
    return run_model("SVM", SVC(), params,
                     X_train, X_test, Y_train, Y_test)

def run_tree(X_train, X_test, Y_train, Y_test):
    params = {
        "criterion": ["gini", "entropy"],
        "splitter": ["best", "random"],
        "max_depth": [2 * n for n in range(1, 10)],
        "max_features": ["auto", "sqrt"],
        "min_samples_leaf": [1, 2, 4],
        "min_samples_split": [2, 5, 10],}
    return run_model("Decision Tree", DecisionTreeClassifier(), params, X_train, X_test, Y_train, Y_test)

def run_knn(X_train, X_test, Y_train, Y_test):
    params = {
        "n_neighbors": list(range(1, 11)),
        "algorithm": ["auto", "ball_tree", "kd_tree", "brute"],
        "p": [1, 2],}
    return run_model("KNN",KNeighborsClassifier(), params, X_train, X_test, Y_train, Y_test)

In [7]:
cm_lr, acc_lr, logreg_cv = run_logreg(X_train, X_test, Y_train, Y_test)
cm_svm, acc_svm, svm_cv = run_svm(X_train, X_test, Y_train, Y_test)
cm_tree, acc_tree, tree_cv = run_tree(X_train, X_test, Y_train, Y_test)
cm_knn, acc_knn, knn_cv    = run_knn(X_train, X_test, Y_train, Y_test)

res = {"LogReg": acc_lr, "SVM":    acc_svm,"Tree":   acc_tree,"KNN":    acc_knn,}
res

Logistic Regression best params : {'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}
Logistic Regression CV accuracy: 0.8464285714285713
Logistic Regression test acc   : 0.8333333333333334
Confusion matrix:
 [[ 3  3]
 [ 0 12]] 

SVM best params : {'C': 1.0, 'gamma': 0.03162277660168379, 'kernel': 'sigmoid'}
SVM CV accuracy: 0.8482142857142856
SVM test acc   : 0.8333333333333334
Confusion matrix:
 [[ 3  3]
 [ 0 12]] 



/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:547: FitFailedWarning: 
3240 fits failed out of a total of 6480.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3240 fits failed with the following error:
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/lib/python3.12/site-packages/sklearn/base.py", line 1467, in wrapper
    estimator._validate_params()
  File "/lib/python3.12/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_p

Decision Tree best params : {'criterion': 'gini', 'max_depth': 6, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 5, 'splitter': 'random'}
Decision Tree CV accuracy: 0.875
Decision Tree test acc   : 0.8333333333333334
Confusion matrix:
 [[ 3  3]
 [ 0 12]] 

KNN best params : {'algorithm': 'auto', 'n_neighbors': 10, 'p': 1}
KNN CV accuracy: 0.8482142857142858
KNN test acc   : 0.8333333333333334
Confusion matrix:
 [[ 3  3]
 [ 0 12]] 



{'LogReg': 0.8333333333333334,
 'SVM': 0.8333333333333334,
 'Tree': 0.8333333333333334,
 'KNN': 0.8333333333333334}

In [8]:
print(res)

{'LogReg': 0.8333333333333334, 'SVM': 0.8333333333333334, 'Tree': 0.8333333333333334, 'KNN': 0.8333333333333334}


In [9]:

X_all_scaled = transform.transform(X)

reuse_pred = logreg_cv.predict(X_all_scaled)        
reuse_prob = logreg_cv.predict_proba(X_all_scaled)[:, 1]     

C_reuse = 62
C_exp   = 165
expected_cost = reuse_prob * C_reuse + (1 - reuse_prob) * C_exp

priced_df = data.copy()
priced_df['PredictedReuse']    = reuse_pred
priced_df['ReuseProbability']  = reuse_prob
priced_df['ExpectedCost_MUSD'] = expected_cost

priced_df.head(10)


FlightNumber        Date BoosterVersion  PayloadMass Orbit    LaunchSite  \
0             1  2010-06-04       Falcon 9  6104.959412   LEO  CCAFS SLC 40   
1             2  2012-05-22       Falcon 9   525.000000   LEO  CCAFS SLC 40   
2             3  2013-03-01       Falcon 9   677.000000   ISS  CCAFS SLC 40   
3             4  2013-09-29       Falcon 9   500.000000    PO   VAFB SLC 4E   
4             5  2013-12-03       Falcon 9  3170.000000   GTO  CCAFS SLC 40   
5             6  2014-01-06       Falcon 9  3325.000000   GTO  CCAFS SLC 40   
6             7  2014-04-18       Falcon 9  2296.000000   ISS  CCAFS SLC 40   
7             8  2014-07-14       Falcon 9  1316.000000   LEO  CCAFS SLC 40   
8             9  2014-08-05       Falcon 9  4535.000000   GTO  CCAFS SLC 40   
9            10  2014-09-07       Falcon 9  4428.000000   GTO  CCAFS SLC 40   

       Outcome  Flights  GridFins  Reused  ...  LandingPad Block  ReusedCount  \
0    None None        1     False   False  ...         NaN   1.0            0   
1    None None        1     False   False  ...         NaN   1.0            0   
2    None None        1     False   False  ...         NaN   1.0            0   
3  False Ocean        1     False   False  ...         NaN   1.0            0   
4    None None        1     False   False  ...         NaN   1.0            0   
5    None None        1     False   False  ...         NaN   1.0            0   
6   True Ocean        1     False   False  ...         NaN   1.0            0   
7   True Ocean        1     False   False  ...         NaN   1.0            0   
8    None None        1     False   False  ...         NaN   1.0            0   
9    None None        1     False   False  ...         NaN   1.0            0   

   Serial   Longitude   Latitude  Class  PredictedReuse  ReuseProbability  \
0   B0003  -80.577366  28.561857      0               0          0.415620   
1   B0005  -80.577366  28.561857      0               0          0.337540   
2   B0007  -80.577366  28.561857      0               0          0.314561   
3   B1003 -120.610829  34.632093      0               0          0.401008   
4   B1004  -80.577366  28.561857      0               0          0.299912   
5   B1005  -80.577366  28.561857      0               0          0.300373   
6   B1006  -80.577366  28.561857      1               1          0.614938   
7   B1007  -80.577366  28.561857      1               1          0.639046   
8   B1008  -80.577366  28.561857      0               0          0.302425   
9   B1011  -80.577366  28.561857      0               0          0.302654   

   ExpectedCost_MUSD  
0         122.191108  
1         130.233374  
2         132.600224  
3         123.696204  
4         134.109050  
5         134.061553  
6         101.661393  
7          99.178279  
8         133.850202  
9         133.826685  

[10 rows x 21 columns]